<?php

return [
    /*
    | City anchors mirror EventSeeder::CITY_ANCHORS. Events are jittered within
    | ~0.5° of each anchor, so nearest-city lookup matches the seeded dataset.
    */
    'anchors' => [
        ['slug' => 'new-york', 'name' => 'New York, NY', 'lat' => 40.7128, 'lng' => -74.0060, 'timezone' => 'America/New_York'],
        ['slug' => 'los-angeles', 'name' => 'Los Angeles, CA', 'lat' => 34.0522, 'lng' => -118.2437, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'chicago', 'name' => 'Chicago, IL', 'lat' => 41.8781, 'lng' => -87.6298, 'timezone' => 'America/Chicago'],
        ['slug' => 'houston', 'name' => 'Houston, TX', 'lat' => 29.7604, 'lng' => -95.3698, 'timezone' => 'America/Chicago'],
        ['slug' => 'phoenix', 'name' => 'Phoenix, AZ', 'lat' => 33.4484, 'lng' => -112.0740, 'timezone' => 'America/Phoenix'],
        ['slug' => 'philadelphia', 'name' => 'Philadelphia, PA', 'lat' => 39.9526, 'lng' => -75.1652, 'timezone' => 'America/New_York'],
        ['slug' => 'san-antonio', 'name' => 'San Antonio, TX', 'lat' => 29.4241, 'lng' => -98.4936, 'timezone' => 'America/Chicago'],
        ['slug' => 'san-diego', 'name' => 'San Diego, CA', 'lat' => 32.7157, 'lng' => -117.1611, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'dallas', 'name' => 'Dallas, TX', 'lat' => 32.7767, 'lng' => -96.7970, 'timezone' => 'America/Chicago'],
        ['slug' => 'san-jose', 'name' => 'San Jose, CA', 'lat' => 37.3382, 'lng' => -121.8863, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'austin', 'name' => 'Austin, TX', 'lat' => 30.2672, 'lng' => -97.7431, 'timezone' => 'America/Chicago'],
        ['slug' => 'san-francisco', 'name' => 'San Francisco, CA', 'lat' => 37.7749, 'lng' => -122.4194, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'seattle', 'name' => 'Seattle, WA', 'lat' => 47.6062, 'lng' => -122.3321, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'denver', 'name' => 'Denver, CO', 'lat' => 39.7392, 'lng' => -104.9903, 'timezone' => 'America/Denver'],
        ['slug' => 'boston', 'name' => 'Boston, MA', 'lat' => 42.3601, 'lng' => -71.0589, 'timezone' => 'America/New_York'],
        ['slug' => 'las-vegas', 'name' => 'Las Vegas, NV', 'lat' => 36.1699, 'lng' => -115.1398, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'miami', 'name' => 'Miami, FL', 'lat' => 25.7617, 'lng' => -80.1918, 'timezone' => 'America/New_York'],
        ['slug' => 'atlanta', 'name' => 'Atlanta, GA', 'lat' => 33.7490, 'lng' => -84.3880, 'timezone' => 'America/New_York'],
        ['slug' => 'washington-dc', 'name' => 'Washington, DC', 'lat' => 38.9072, 'lng' => -77.0369, 'timezone' => 'America/New_York'],
        ['slug' => 'nashville', 'name' => 'Nashville, TN', 'lat' => 36.1627, 'lng' => -86.7816, 'timezone' => 'America/Chicago'],
        ['slug' => 'portland', 'name' => 'Portland, OR', 'lat' => 45.5152, 'lng' => -122.6784, 'timezone' => 'America/Los_Angeles'],
        ['slug' => 'new-orleans', 'name' => 'New Orleans, LA', 'lat' => 29.9511, 'lng' => -90.0715, 'timezone' => 'America/Chicago'],
        ['slug' => 'toronto', 'name' => 'Toronto, ON', 'lat' => 43.6532, 'lng' => -79.3832, 'timezone' => 'America/Toronto'],
        ['slug' => 'montreal', 'name' => 'Montreal, QC', 'lat' => 45.5019, 'lng' => -73.5674, 'timezone' => 'America/Toronto'],
        ['slug' => 'vancouver', 'name' => 'Vancouver, BC', 'lat' => 49.2827, 'lng' => -123.1207, 'timezone' => 'America/Vancouver'],
        ['slug' => 'calgary', 'name' => 'Calgary, AB', 'lat' => 51.0447, 'lng' => -114.0719, 'timezone' => 'America/Edmonton'],
        ['slug' => 'ottawa', 'name' => 'Ottawa, ON', 'lat' => 45.4215, 'lng' => -75.6972, 'timezone' => 'America/Toronto'],
        ['slug' => 'edmonton', 'name' => 'Edmonton, AB', 'lat' => 53.5461, 'lng' => -113.4938, 'timezone' => 'America/Edmonton'],
        ['slug' => 'quebec-city', 'name' => 'Quebec City, QC', 'lat' => 46.8139, 'lng' => -71.2080, 'timezone' => 'America/Toronto'],
        ['slug' => 'winnipeg', 'name' => 'Winnipeg, MB', 'lat' => 49.8951, 'lng' => -97.1384, 'timezone' => 'America/Winnipeg'],
        ['slug' => 'mexico-city', 'name' => 'Mexico City, MX', 'lat' => 19.4326, 'lng' => -99.1332, 'timezone' => 'America/Mexico_City'],
        ['slug' => 'guadalajara', 'name' => 'Guadalajara, MX', 'lat' => 20.6597, 'lng' => -103.3496, 'timezone' => 'America/Mexico_City'],
        ['slug' => 'monterrey', 'name' => 'Monterrey, MX', 'lat' => 25.6866, 'lng' => -100.3161, 'timezone' => 'America/Monterrey'],
        ['slug' => 'puebla', 'name' => 'Puebla, MX', 'lat' => 19.0414, 'lng' => -98.2063, 'timezone' => 'America/Mexico_City'],
        ['slug' => 'tijuana', 'name' => 'Tijuana, MX', 'lat' => 32.5149, 'lng' => -117.0382, 'timezone' => 'America/Tijuana'],
        ['slug' => 'cancun', 'name' => 'Cancún, MX', 'lat' => 21.1619, 'lng' => -86.8515, 'timezone' => 'America/Cancun'],
        ['slug' => 'merida', 'name' => 'Mérida, MX', 'lat' => 20.9674, 'lng' => -89.5926, 'timezone' => 'America/Merida'],
        ['slug' => 'london', 'name' => 'London, UK', 'lat' => 51.5074, 'lng' => -0.1278, 'timezone' => 'Europe/London'],
        ['slug' => 'paris', 'name' => 'Paris, France', 'lat' => 48.8566, 'lng' => 2.3522, 'timezone' => 'Europe/Paris'],
        ['slug' => 'berlin', 'name' => 'Berlin, Germany', 'lat' => 52.5200, 'lng' => 13.4050, 'timezone' => 'Europe/Berlin'],
        ['slug' => 'madrid', 'name' => 'Madrid, Spain', 'lat' => 40.4168, 'lng' => -3.7038, 'timezone' => 'Europe/Madrid'],
        ['slug' => 'rome', 'name' => 'Rome, Italy', 'lat' => 41.9028, 'lng' => 12.4964, 'timezone' => 'Europe/Rome'],
        ['slug' => 'amsterdam', 'name' => 'Amsterdam, NL', 'lat' => 52.3676, 'lng' => 4.9041, 'timezone' => 'Europe/Amsterdam'],
        ['slug' => 'barcelona', 'name' => 'Barcelona, Spain', 'lat' => 41.3851, 'lng' => 2.1734, 'timezone' => 'Europe/Madrid'],
        ['slug' => 'munich', 'name' => 'Munich, Germany', 'lat' => 48.1351, 'lng' => 11.5820, 'timezone' => 'Europe/Berlin'],
        ['slug' => 'milan', 'name' => 'Milan, Italy', 'lat' => 45.4642, 'lng' => 9.1900, 'timezone' => 'Europe/Rome'],
        ['slug' => 'vienna', 'name' => 'Vienna, Austria', 'lat' => 48.2082, 'lng' => 16.3738, 'timezone' => 'Europe/Vienna'],
        ['slug' => 'prague', 'name' => 'Prague, Czechia', 'lat' => 50.0755, 'lng' => 14.4378, 'timezone' => 'Europe/Prague'],
        ['slug' => 'lisbon', 'name' => 'Lisbon, Portugal', 'lat' => 38.7223, 'lng' => -9.1393, 'timezone' => 'Europe/Lisbon'],
        ['slug' => 'dublin', 'name' => 'Dublin, Ireland', 'lat' => 53.3498, 'lng' => -6.2603, 'timezone' => 'Europe/Dublin'],
        ['slug' => 'copenhagen', 'name' => 'Copenhagen, Denmark', 'lat' => 55.6761, 'lng' => 12.5683, 'timezone' => 'Europe/Copenhagen'],
        ['slug' => 'stockholm', 'name' => 'Stockholm, Sweden', 'lat' => 59.3293, 'lng' => 18.0686, 'timezone' => 'Europe/Stockholm'],
        ['slug' => 'oslo', 'name' => 'Oslo, Norway', 'lat' => 59.9139, 'lng' => 10.7522, 'timezone' => 'Europe/Oslo'],
        ['slug' => 'helsinki', 'name' => 'Helsinki, Finland', 'lat' => 60.1699, 'lng' => 24.9384, 'timezone' => 'Europe/Helsinki'],
        ['slug' => 'brussels', 'name' => 'Brussels, Belgium', 'lat' => 50.8503, 'lng' => 4.3517, 'timezone' => 'Europe/Brussels'],
        ['slug' => 'zurich', 'name' => 'Zurich, Switzerland', 'lat' => 47.3769, 'lng' => 8.5417, 'timezone' => 'Europe/Zurich'],
        ['slug' => 'warsaw', 'name' => 'Warsaw, Poland', 'lat' => 52.2297, 'lng' => 21.0122, 'timezone' => 'Europe/Warsaw'],
        ['slug' => 'budapest', 'name' => 'Budapest, Hungary', 'lat' => 47.4979, 'lng' => 19.0402, 'timezone' => 'Europe/Budapest'],
        ['slug' => 'athens', 'name' => 'Athens, Greece', 'lat' => 37.9838, 'lng' => 23.7275, 'timezone' => 'Europe/Athens'],
        ['slug' => 'lyon', 'name' => 'Lyon, France', 'lat' => 45.7640, 'lng' => 4.8357, 'timezone' => 'Europe/Paris'],
        ['slug' => 'hamburg', 'name' => 'Hamburg, Germany', 'lat' => 53.5511, 'lng' => 9.9937, 'timezone' => 'Europe/Berlin'],
        ['slug' => 'manchester', 'name' => 'Manchester, UK', 'lat' => 53.4808, 'lng' => -2.2426, 'timezone' => 'Europe/London'],
        ['slug' => 'edinburgh', 'name' => 'Edinburgh, UK', 'lat' => 55.9533, 'lng' => -3.1883, 'timezone' => 'Europe/London'],
        ['slug' => 'frankfurt', 'name' => 'Frankfurt, Germany', 'lat' => 50.1109, 'lng' => 8.6821, 'timezone' => 'Europe/Berlin'],
        ['slug' => 'krakow', 'name' => 'Kraków, Poland', 'lat' => 50.0647, 'lng' => 19.9450, 'timezone' => 'Europe/Warsaw'],
        ['slug' => 'porto', 'name' => 'Porto, Portugal', 'lat' => 41.1579, 'lng' => -8.6291, 'timezone' => 'Europe/Lisbon'],
        ['slug' => 'naples', 'name' => 'Naples, Italy', 'lat' => 40.8518, 'lng' => 14.2681, 'timezone' => 'Europe/Rome'],
        ['slug' => 'tokyo', 'name' => 'Tokyo, Japan', 'lat' => 35.6762, 'lng' => 139.6503, 'timezone' => 'Asia/Tokyo'],
        ['slug' => 'seoul', 'name' => 'Seoul, South Korea', 'lat' => 37.5665, 'lng' => 126.9780, 'timezone' => 'Asia/Seoul'],
        ['slug' => 'singapore', 'name' => 'Singapore', 'lat' => 1.3521, 'lng' => 103.8198, 'timezone' => 'Asia/Singapore'],
        ['slug' => 'sydney', 'name' => 'Sydney, Australia', 'lat' => -33.8688, 'lng' => 151.2093, 'timezone' => 'Australia/Sydney'],
        ['slug' => 'melbourne', 'name' => 'Melbourne, Australia', 'lat' => -37.8136, 'lng' => 144.9631, 'timezone' => 'Australia/Melbourne'],
        ['slug' => 'dubai', 'name' => 'Dubai, UAE', 'lat' => 25.2048, 'lng' => 55.2708, 'timezone' => 'Asia/Dubai'],
        ['slug' => 'sao-paulo', 'name' => 'São Paulo, Brazil', 'lat' => -23.5505, 'lng' => -46.6333, 'timezone' => 'America/Sao_Paulo'],
        ['slug' => 'buenos-aires', 'name' => 'Buenos Aires, Argentina', 'lat' => -34.6037, 'lng' => -58.3816, 'timezone' => 'America/Argentina/Buenos_Aires'],
    ],

    'placeholders' => [
        'images/events/placeholder-1.svg',
        'images/events/placeholder-2.svg',
        'images/events/placeholder-3.svg',
        'images/events/placeholder-4.svg',
    ],
];
